version: '2.3'

services:
  discounts:
    build: discounts/
    ports:
      - 9229:9229
      - 3000:3000
    command: sh -c "sh ./scripts/wait.sh mariadb && npm start"
    depends_on:
      - mariadb
    networks:
      - api

  products:
    build: products/
    ports:
      - 5000:5000
      - 5005:5005
    depends_on:
      - mariadb
    networks:
      - api
    command: sh -c "sh ./scripts/wait.sh mariadb && java -jar products.jar"
    environment:
      DISCOUNTS_SERVER: discounts
      DISCOUNTS_PORT: 3000
      DATABASE_URI: jdbc:mysql://mariadb/chumlee
      DATABASE_USER: dev
      DATABASE_PASSWORD: CHUML33
      SERVER_PORT: 5000
      JAVA_TOOL_OPTIONS: >
        -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

  mariadb:
    image: mariadb:10
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=chumlee
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=CHUML33
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - mysql-data:/etc/mysql/conf.d
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - api

volumes:
  mysql-data:
    driver: local

networks:
  api:
